apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: federation-etcd
  name: federation-etcd
  namespace: federation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: federation-etcd
  template:
    metadata:
      labels:
        app: federation-etcd
    spec:
      containers:
      - args:
        - --name=$(MEMBER_NAME)
        - --initial-advertise-peer-urls=http://$(MEMBER_IP):32380
        - --listen-peer-urls=http://0.0.0.0:2380
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://$(MEMBER_IP):32379
        - --initial-cluster-token=$(CLUSTER_TOKEN)
        - --initial-cluster=$(INITIAL_CLUSTER)
        - --initial-cluster-state=new
        command:
        - etcd
        env:
          - name: CLUSTER_TOKEN
            valueFrom:
              configMapKeyRef:
                name: federation-etcd
                key: cluster-token
          - name: INITIAL_CLUSTER
            valueFrom:
              configMapKeyRef:
                name: federation-etcd
                key: initial-cluster
          - name: MEMBER_IP
            valueFrom:
              configMapKeyRef:
                name: federation-etcd
                key: member-ip
          - name: MEMBER_NAME
            valueFrom:
              configMapKeyRef:
                name: federation-etcd
                key: member-name
        image: quay.io/coreos/etcd:v3.0.7
        imagePullPolicy: IfNotPresent
        name: etcd
        ports:
        - containerPort: 2379
          protocol: TCP
        - containerPort: 2380
          protocol: TCP
      restartPolicy: Always
