apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: federation-apiserver
  namespace: federation
  labels:
    app: federated-cluster
spec:
  template:
    metadata:
      name: federation-apiserver
      labels:
        app: federated-cluster
        module: federation-apiserver
    spec:
      containers:
      - name: apiserver
        image: gcr.io/google_containers/hyperkube-amd64:v1.6.0
        env:
          - name: ADVERTISE_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: federation-apiserver
                key: advertise-address
          - name: ETCD_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: federation-apiserver
                key: etcd-address
        command:
          - /hyperkube
          - federation-apiserver
          - --bind-address=0.0.0.0
          - --etcd-servers=http://$(ETCD_ADDRESS):2379
          - --secure-port=443
          - --advertise-address=$(ADVERTISE_ADDRESS)
          - --token-auth-file=/srv/kubernetes/known-tokens.csv
        ports:
          - containerPort: 443
            name: https
          - containerPort: 8080
            name: local
        volumeMounts:
          - name: federation-apiserver-secrets
            mountPath: /srv/kubernetes/
            readOnly: true
      nodeSelector:
        node-role.kubernetes.io/master: ''
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      volumes:
        - name: federation-apiserver-secrets
          secret:
            secretName: federation-apiserver-secrets
